// <auto-generated />
using DictionaryApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DictionaryApp.Migrations
{
    [DbContext(typeof(DictContext))]
    [Migration("20210703125826_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("DictionaryApp.Models.Noun", b =>
                {
                    b.Property<int>("NounId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NounId");

                    b.HasIndex("WordId");

                    b.ToTable("Nouns");
                });

            modelBuilder.Entity("DictionaryApp.Models.Word", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("text")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("DictionaryApp.Models.Noun", b =>
                {
                    b.HasOne("DictionaryApp.Models.Word", "word")
                        .WithMany("nouns")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("word");
                });

            modelBuilder.Entity("DictionaryApp.Models.Word", b =>
                {
                    b.Navigation("nouns");
                });
#pragma warning restore 612, 618
        }
    }
}
