// <auto-generated />
using DictionaryApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DictionaryApp.Migrations
{
    [DbContext(typeof(DictContext))]
    [Migration("20210705062502_creating")]
    partial class creating
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("DictionaryApp.Models.Noun", b =>
                {
                    b.Property<int>("NounId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NounId");

                    b.HasIndex("WordId");

                    b.ToTable("Nouns");
                });

            modelBuilder.Entity("DictionaryApp.Models.Sentence", b =>
                {
                    b.Property<int>("SentenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SentenceText")
                        .HasColumnType("TEXT");

                    b.HasKey("SentenceId");

                    b.ToTable("Sentence");
                });

            modelBuilder.Entity("DictionaryApp.Models.Word", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("text")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("DictionaryApp.Models.WordSentence", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SentenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("SentenceId");

                    b.HasIndex("WordId");

                    b.ToTable("WordSentence");
                });

            modelBuilder.Entity("DictionaryApp.Models.Noun", b =>
                {
                    b.HasOne("DictionaryApp.Models.Word", "word")
                        .WithMany("nouns")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("word");
                });

            modelBuilder.Entity("DictionaryApp.Models.WordSentence", b =>
                {
                    b.HasOne("DictionaryApp.Models.Sentence", "Sentence")
                        .WithMany("wordSentences")
                        .HasForeignKey("SentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DictionaryApp.Models.Word", "Word")
                        .WithMany("wordSentences")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sentence");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("DictionaryApp.Models.Sentence", b =>
                {
                    b.Navigation("wordSentences");
                });

            modelBuilder.Entity("DictionaryApp.Models.Word", b =>
                {
                    b.Navigation("nouns");

                    b.Navigation("wordSentences");
                });
#pragma warning restore 612, 618
        }
    }
}
